default: &default
  adapter: postgresql
  encoding: unicode
  username: miya 
  password: miya
  host: localhost
  pool: 5

development:
  <<: *default
  database: inventariomilu

test:
  <<: *default
  database: inventariomilu_test

production:
  <<: *default
  database: inventariomilu_production
  username: admin
  password: admin
